# Generated by Django 4.0.5 on 2022-07-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Entregables',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiantes',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesores',
        ),
    ]
